### ISSUE TITLE
inferPolyASites Error

### ISSUE THREAD

**Issue by mossnicholas** [argschwind/TAPseq#3]
Hi,

I'm running inferPolyASites with default parameters, and receive the following error:
```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘Views’ for signature ‘"NULL"’
```
Is this an error that pertains to my input list of GRanges or BAM file?

**Comment by argschwind** [comment]
Hi,

Does the example in the documentation of inferPolyASites work? The package contains a small bam file for that.

Views is used to extract the read coverage of a given gene from the bam file:
```
gene_cvrg <- Views(coverage[[chr]], ranges(exons))
```

I suspect your problem has to do with the bam file, e.g. chromosome names in the bam file not matching the ones in your GRanges of genes ("chr1" vs. "1").
