### ISSUE TITLE
Primers only designed to 3' ends for transcripts in forward orientation

### ISSUE THREAD

**Issue by joebowness** [argschwind/TAPseq#4]
Hello!

Thank for this great resource. For the most part the vignette you have made is great and very easy to understand and replicate. I am trying to apply the TAPseq primer design pipeline to a set of genes from the mouse genome (mm10). 

The steps for polyA site detection and truncation of 3’ ends of transcripts seem to be working well, and for genes in the forward orientation I can run the primer design pipeline to design inner and outer primers in the correct locations to capture from the 3’ ends of transcripts. However, for reverse-oriented transcripts the primers are still designed relative to the higher genomic coordinates (ie. right hand side), so to the 5’ ends rather than 3’ ends of transcripts. Attached are URLs with two screenshots of example genes that illustrate the issue I am having (outer primers=blue, inner primers=gold).

[https://ibb.co/d7p377z](https://ibb.co/d7p377z)
[https://ibb.co/zb3HhrY](https://ibb.co/zb3HhrY)

Is there something I am missing (likely in the following 3 commands) which retains the strandedness of transcript sequences, and thus means primers are designed correctly to the 3’ ends for genes in reverse orientation?

```
# extract sequences of truncated transcripts
library(BSgenome)
mm10 <- getBSgenome("BSgenome.Mmusculus.UCSC.mm10")

# get sequence for all truncated transcripts
txs_seqs <- getTxsSeq(truncated_txs, genome = mm10)

# create TAPseq IO for outer forward primers from truncated transcript sequences
outer_primers <- TAPseqInput(txs_seqs, target_annot = truncated_txs,
                             product_size_range = c(500, 700), primer_num_return = 5)
```

This might be silly question with an easy fix, but as far as I can tell I am following the commands from the example vignette exactly, so for the moment I am stumped.
 
Many thanks in advance for any assistance you can offer!
Joe

**Comment by argschwind** [comment]
Hi Joe,

Thanks for reaching out about this. There is a bug in the createPrimerTrack() function that doesn't correctly convert transcript coordinates to genome coordinates. I'm currently testing a fix for that and will push it in the coming days. I can keep you posted here, once it's up.

The good news are, that the bug only seems to affect the visualization of primer binding sites. The primer sequences themselves should be fine.

Cheers,
Andreas

**Comment by joebowness** [comment]
Hi Andreas, 

Thanks for getting back to me so quickly. I hadn't considered that the bug might be in the creation of the Primer tracks rather than the primer generation - that is reassuring to know!

For my purposes it will still be quite important to visualise each designed primer set in relation to the transcripts, so I would definitely appreciate the bug fix for the createPrimerTrack() and keen to be informed when it is up!

Many thanks,

Joe

**Comment by argschwind** [comment]
Hi Joe,

I uploaded a fix to the master branch. Could you install the package from there and see if that solves the issue?

```
# latest development version
devtools::install_github("argschwind/TAPseq", dependencies = TRUE)
```

**Comment by joebowness** [comment]
Hi Andreas,

The update seems to have fully fixed the primer visualisation issue - many thanks for uploading the fix so quickly!

[https://ibb.co/w6yJYS5](https://ibb.co/w6yJYS5)

Cheers,
Joe

**Comment by Martin-Fahrenberger** [comment]
Hi Andreas,

I ran into this same issue last week because I installed the TAPseq package from Bioconductor.
While installing it through
`devtools::install_github("argschwind/TAPseq", dependencies = TRUE)`
fixed the issue, it would be nice if you could update the bioconductor version too.

thanks,
Martin
